DROP TABLE USERS, FRIENDS, CITIES, USER_CURRENT_CITIES, USER_HOMETOWN_CITIES, MESSAGES, PROGRAMS, EDUCATION, USER_EVENTS, PARTICIPANTS, ALBUMS, PHOTOS, TAGS;
DROP TRIGGER order_friends_pairs;
/*done*/

